-- Applied remotely as expand_goal_kind_presets + league_create_and_check_rpcs
-- create_league / submit_goal_check / start_timer_session / pause_timer_session / finish_timer_session
-- 순위 분배 인자는 create_league_rank_weights.sql 참고
