import { useRef, useState } from 'react';
import { Image, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as Haptics from 'expo-haptics';
import { Camera, Check, RotateCcw, SkipForward, Video } from 'lucide-react-native';
import { AppHeader, InlineNotice, PrimaryAction, ScreenContainer } from '../components/ui';
import { color, radius, space, type } from '../design/tokens';

export function CaptureScreen({ back, done }: { back: () => void; done: () => void }) {
  const camera = useRef<CameraView>(null);
  const [permission, requestPermission] = useCameraPermissions();
  const [photo, setPhoto] = useState<string | null>(null);
  const [video, setVideo] = useState<string | null>(null);
  const [recording, setRecording] = useState(false);
  const takePhoto = async () => { const result = await camera.current?.takePictureAsync({ quality: 0.7 }); if (result?.uri) { setPhoto(result.uri); if (Platform.OS !== 'web') await Haptics.selectionAsync(); } };
  const takeVideo = async () => { setRecording(true); try { const result = await camera.current?.recordAsync({ maxDuration: 2 }); if (result?.uri) setVideo(result.uri); } finally { setRecording(false); } };
  if (!permission) return <ScreenContainer><AppHeader title="리캡 촬영" onBack={back} /><InlineNotice title="카메라 권한을 확인하고 있어요" /></ScreenContainer>;
  if (!permission.granted) return <ScreenContainer><AppHeader title="리캡 촬영" onBack={back} /><View style={styles.permission}><Camera size={30} color={color.blue} /><Text style={styles.heading}>카메라 권한이 필요해요</Text><Text style={styles.body}>수행 직후의 사진과 2초 영상을 비공개 리캡에 저장합니다. 권한을 거절해도 기록 제출은 가능합니다.</Text><PrimaryAction label="카메라 권한 허용" icon={Camera} onPress={requestPermission} /><PrimaryAction label="이번에는 건너뛰기" icon={SkipForward} tone="quiet" onPress={done} /></View></ScreenContainer>;
  return <View style={styles.full}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back" mode={photo ? 'video' : 'picture'} mute={false} /><View style={styles.top}><AppHeader title="리캡 촬영" subtitle={photo ? '2초 영상을 이어서 촬영하세요' : '먼저 사진 한 장을 남겨요'} onBack={back} /></View>{photo ? <Image source={{ uri: photo }} style={styles.thumb} /> : null}<View style={styles.controls}>{video ? <View style={styles.done}><Check size={20} color={color.ink} /><Text style={styles.doneText}>사진과 2초 영상을 담았어요</Text></View> : null}<View style={styles.actions}>{photo ? <Pressable accessibilityRole="button" accessibilityLabel="다시 촬영" style={styles.secondary} onPress={() => { setPhoto(null); setVideo(null); }}><RotateCcw size={22} color={color.white} /></Pressable> : null}<Pressable accessibilityRole="button" accessibilityLabel={photo ? '2초 영상 촬영' : '사진 촬영'} disabled={recording} style={[styles.shutter, recording && styles.recording]} onPress={photo ? takeVideo : takePhoto}>{photo ? <Video size={25} color={color.ink} /> : <Camera size={25} color={color.ink} />}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="건너뛰기" style={styles.secondary} onPress={done}><SkipForward size={22} color={color.white} /></Pressable></View>{video ? <PrimaryAction label="리캡에 비공개 저장" icon={Check} onPress={done} /> : <Text style={styles.hint}>{recording ? '2초를 기록하는 중…' : photo ? '버튼을 누르면 2초 후 자동으로 멈춰요' : '사진은 확정된 기록과 함께만 표시돼요'}</Text>}</View></View>;
}

const styles = StyleSheet.create({ full: { flex: 1, backgroundColor: color.ink }, top: { position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: space.x5, backgroundColor: 'rgba(246,244,239,0.92)' }, permission: { flex: 1, minHeight: 620, justifyContent: 'center', alignItems: 'center', gap: space.x4, maxWidth: 440, alignSelf: 'center' }, heading: { color: color.ink, ...type.heading, textAlign: 'center' }, body: { color: color.inkMuted, ...type.body, textAlign: 'center' }, thumb: { position: 'absolute', top: 92, right: space.x5, width: 76, height: 104, borderRadius: radius.input, borderWidth: 2, borderColor: color.white }, controls: { position: 'absolute', left: space.x5, right: space.x5, bottom: space.x6, gap: space.x3 }, actions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: space.x5 }, shutter: { width: 72, height: 72, borderRadius: 36, backgroundColor: color.aqua, borderWidth: 5, borderColor: color.white, alignItems: 'center', justifyContent: 'center' }, recording: { backgroundColor: color.orange }, secondary: { width: 48, height: 48, borderRadius: 24, backgroundColor: color.blue, alignItems: 'center', justifyContent: 'center' }, hint: { color: color.white, ...type.caption, textAlign: 'center' }, done: { alignSelf: 'center', borderRadius: radius.input, backgroundColor: color.lime, paddingHorizontal: space.x4, minHeight: 44, flexDirection: 'row', gap: space.x2, alignItems: 'center' }, doneText: { color: color.ink, ...type.label } });
